In [34]:
from tensorflow.keras.preprocessing.text import one_hot

In [35]:
## Sentence 
sentence=['the glass of milk', 'the glass of juice ', 'the cup of tea', 'I am a good boy', 'understand the meaning of words','your videos are good']  ## this is the(corpus).

In [36]:
sentence

['the glass of milk',
 'the glass of juice ',
 'the cup of tea',
 'I am a good boy',
 'understand the meaning of words',
 'your videos are good']

In [37]:
##  Define the vocabulary size 
voc_size =10000

This one_hot is not exactly classical one-hot encoding, but rather a hashing trick:

It converts words in a sentence into integers between 1 and voc_size.

In [38]:
## One-hot Representation,   
one_hot_repre = [one_hot(words,voc_size) for words in sentence]
one_hot_repre

[[8275, 8122, 2833, 6354],
 [8275, 8122, 2833, 1983],
 [8275, 6656, 2833, 8193],
 [1457, 8808, 3496, 7470, 7507],
 [8789, 8275, 7286, 2833, 2067],
 [8120, 591, 1297, 7470]]

In [39]:
for words in sentence:
    print(f"{words}\n")

the glass of milk

the glass of juice 

the cup of tea

I am a good boy

understand the meaning of words

your videos are good



pca->300 dimentions->2 dimention
the similar items are will be close in 2d like mango and apples are near(less distance ) because of the they are fruits(similaryity)

### cosine similarity-> recommandation system.  


                        -------------------------
                        |                       |
                        |                       |
encoded words---------->|        EMBEDDING      |-----> word embeddings.
                        |        LAYER          |
                        |                       |
                        -------------------------

In [40]:
## word Embedding Representation.
from tensorflow.keras.layers  import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

There we have different length of sentence but for training purpose we have to make all the sentences into same size.

In [41]:
sent_length = 8
embedding_doc = pad_sequences(one_hot_repre,maxlen=sent_length,padding='pre')
print(embedding_doc)

[[   0    0    0    0 8275 8122 2833 6354]
 [   0    0    0    0 8275 8122 2833 1983]
 [   0    0    0    0 8275 6656 2833 8193]
 [   0    0    0 1457 8808 3496 7470 7507]
 [   0    0    0 8789 8275 7286 2833 2067]
 [   0    0    0    0 8120  591 1297 7470]]


In [48]:
## Feature representation
dim = 10
model = Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim))
model.build(input_shape=(None,sent_length))
model.compile("adam","mse")

In [49]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [50]:
model.predict(embedding_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step


array([[[-0.01941752, -0.03830229, -0.01822414, -0.04492264,
         -0.0262815 ,  0.0274807 , -0.02941034, -0.02100879,
          0.02516187, -0.02406915],
        [-0.01941752, -0.03830229, -0.01822414, -0.04492264,
         -0.0262815 ,  0.0274807 , -0.02941034, -0.02100879,
          0.02516187, -0.02406915],
        [-0.01941752, -0.03830229, -0.01822414, -0.04492264,
         -0.0262815 ,  0.0274807 , -0.02941034, -0.02100879,
          0.02516187, -0.02406915],
        [-0.01941752, -0.03830229, -0.01822414, -0.04492264,
         -0.0262815 ,  0.0274807 , -0.02941034, -0.02100879,
          0.02516187, -0.02406915],
        [ 0.01969541, -0.00040132, -0.00856922, -0.04914551,
         -0.04435417,  0.01089232, -0.0404256 , -0.00583724,
         -0.04726133, -0.01400479],
        [-0.03286408,  0.03437345, -0.03776078, -0.03439265,
          0.04092412, -0.0466346 ,  0.03091848,  0.00741883,
         -0.01240388, -0.02635911],
        [ 0.02290009, -0.00029739, -0.01346882,  0.0

In [58]:
embedding_doc[0].shape,embedding_doc[0]


((8,), array([   0,    0,    0,    0, 8275, 8122, 2833, 6354], dtype=int32))

In [59]:
model.predict(np.array([embedding_doc[0]]))  ## just converted to 2d array because the embedding_doc[0] is 1d // or another method is np.reshape(embdding_doc[0],(-1,1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[[-0.01941752, -0.03830229, -0.01822414, -0.04492264,
         -0.0262815 ,  0.0274807 , -0.02941034, -0.02100879,
          0.02516187, -0.02406915],
        [-0.01941752, -0.03830229, -0.01822414, -0.04492264,
         -0.0262815 ,  0.0274807 , -0.02941034, -0.02100879,
          0.02516187, -0.02406915],
        [-0.01941752, -0.03830229, -0.01822414, -0.04492264,
         -0.0262815 ,  0.0274807 , -0.02941034, -0.02100879,
          0.02516187, -0.02406915],
        [-0.01941752, -0.03830229, -0.01822414, -0.04492264,
         -0.0262815 ,  0.0274807 , -0.02941034, -0.02100879,
          0.02516187, -0.02406915],
        [ 0.01969541, -0.00040132, -0.00856922, -0.04914551,
         -0.04435417,  0.01089232, -0.0404256 , -0.00583724,
         -0.04726133, -0.01400479],
        [-0.03286408,  0.03437345, -0.03776078, -0.03439265,
          0.04092412, -0.0466346 ,  0.03091848,  0.00741883,
         -0.01240388, -0.02635911],
        [ 0.02290009, -0.00029739, -0.01346882,  0.0

### Here the 0->[-0.01941752, -0.03830229, -0.01822414, -0.04492264,-0.0262815 ,  0.0274807 , -0.02941034, -0.02100879,0.02516187,-0.02406915]

### 8275->[-0.01941752, -0.03830229, -0.01822414, -0.04492264,-0.0262815 ,  0.0274807 , -0.02941034, -0.02100879,0.02516187, -0.02406915]    etc